name: Deploy to Hostinger via SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 🚚 Obter código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🔨 Gerar versão de Produção (Build)
        run: npm run build

      - name: 🚀 Enviar para Hostinger (SFTP/SSH)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 46.202.145.236
          port: 65002
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/*"
          target: "/home/u969433331/public_html/"
          strip_components: 1
          rm: true
